apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: acc-api
  name: acc-api
spec:
  containers:
  - args:
    - serve
    env:
    - name: ACC_API_PORT
      value: "8080"
    image: f5devcentral/f5-automation-config-converter:1.23.0
    name: acc-api
    resources: {}
    volumeMounts:
    - mountPath: /tmp
      name: acc-api-tmpfs0
  restartPolicy: OnFailure
  volumes:
  - emptyDir:
      medium: Memory
    name: acc-api-tmpfs0
status: {}
