apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: celery-worker
  name: celery-worker
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: f5devcentral/f5-bigip-journeys-app:v3.3.5
    generation: null
    importPolicy: {}
    name: v3.3.5
status:
  dockerImageRepository: ""
