apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift -v -f docker-compose.yaml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: celery-worker
  name: celery-worker
spec:
  replicas: 1
  selector:
    io.kompose.service: celery-worker
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: celery-worker
    spec:
      containers:
      - args:
        - celery
        - -A
        - journeys.backend
        - worker
        - -l
        - debug
        env:
        - name: BROKER_URL
          value: redis://redis:6379/0
        image: ' '
        name: celery-worker
        resources: {}
        volumeMounts:
        - mountPath: /migrate
          name: celery-worker-claim0
      restartPolicy: Always
      volumes:
      - name: celery-worker-claim0
        persistentVolumeClaim:
          claimName: celery-worker-claim0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - celery-worker
      from:
        kind: ImageStreamTag
        name: celery-worker:v3.3.5
    type: ImageChange
status: {}
