apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift -v -f docker-compose.yaml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: journeys
  name: journeys
spec:
  replicas: 1
  selector:
    io.kompose.service: journeys
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: journeys
    spec:
      serviceAccount: postgres-root
      containers:
      - args:
        - runserver
        env:
        - name: ACC_API_HOST
          value: acc-api
        - name: ACC_API_PORT
          value: "8080"
        - name: BROKER_URL
          value: redis://redis:6379/0
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          value: postgres
        - name: DB_PASS
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: postgres
        - name: JOURNEYS_PORT
          value: "8443"
        - name: MIGRATE_DIR
          value: /migrate
        image: ' '
        name: journeys
        ports:
        - containerPort: 443
          hostIP: 127.0.0.1
        resources: {}
        volumeMounts:
        - mountPath: /migrate
          name: journeys-claim0
      restartPolicy: Always
      volumes:
      - name: journeys-claim0
        persistentVolumeClaim:
          claimName: journeys-claim0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - journeys
      from:
        kind: ImageStreamTag
        name: journeys:v3.3.5
    type: ImageChange
status: {}
