apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift -v -f docker-compose.yaml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: journeys
  name: journeys
spec:
  ports:
  - name: "8443"
    port: 8443
    targetPort: 443
  selector:
    io.kompose.service: journeys
status:
  loadBalancer: {}
